apiVersion: batch/v1
kind: Job
metadata:
  name: train-models-job
spec:
  template:
    spec:
      containers:
        - name: train-container
          image: xaviervasques/kubernetes-models:latest
          command: []
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
