apiVersion: v1
kind: Pod
metadata:
  name: env-pod

spec:
  containers:
    - name: secret-test
      image: nginx
      command: ['sh', '-c', 'echo "Wandb key: $WANDB_API_KEY"']
      env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-vars
              key: WANDB_API_KEY
      imagePullPolicy: Always
  restartPolicy: Never
  